<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CSLT_chiều_t3</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>CSLT_chiều_t3.buổi3.BT_1</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="buổi1\" />
    <Folder Include="buổi4%28onl%29\" />
  </ItemGroup>

</Project>
